version: '3.8'

services:
  # 1. دیتابیس پستگرس
  postgres:
    image: postgres:15-alpine
    container_name: campaign_postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: campaign_user
      POSTGRES_PASSWORD: campaign_passُ
      POSTGRES_DB: campaign_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d campaign_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # 2. پنل مدیریت دیتابیس (Adminer)
  adminer:
    image: adminer
    container_name: campaign_db_ui
    ports:
      - "1082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: