server:
  address: "0.0.0.0"
  port: "8080"

grpc:
  address: "0.0.0.0"
  port: "50050"

# ğŸ”´ Ù†Ú©ØªÙ‡ Ø­ÛŒØ§ØªÛŒ: Ù†Ø§Ù… Ø§ÛŒÙ† Ú©Ù„ÛŒØ¯ Ø¨Ø§ÛŒØ¯ Ø¨Ø§ mapstructure Ø¯Ø± ÙØ§ÛŒÙ„ config.go ÛŒÚ©ÛŒ Ø¨Ø§Ø´Ø¯
postgresdb:
  host: "localhost"
  port: 5434            # ğŸ‘ˆ Ù¾ÙˆØ±Øª Ø§Ú©Ø³ØªØ±Ù†Ø§Ù„ Ø¯Ø§Ú©Ø± Ø´Ù…Ø§
  user: "campaign_user"       # ğŸ‘ˆ Ø³Øª Ø´Ø¯Ù‡ Ø¯Ø± Docker Env
  password: "campaign_pass"   # ğŸ‘ˆ Ø³Øª Ø´Ø¯Ù‡ Ø¯Ø± Docker Env
  dbname: "campaign_db"
  sslmode: "disable"

  # ØªÙ†Ø¸ÛŒÙ…Ø§Øª Connection Pool
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: "1h"